import type { Metadata } from "next";
import { Inter, Poppins, Roboto_Condensed } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

// const inter = Inter({ subsets: ["latin"] });

// const inter = Inter({
//   subsets: ["latin"],
//   display: "swap",
//   variable: "--font-inter",
// });

// const roboto = Roboto_Condensed({
//   subsets: ["latin"],
//   display: "swap",
//   variable: "--font-roboto",
// });

// const poppins = Poppins({
//   subsets: ["latin"],
//   display: "swap",
//   variable: "--font-poppins",
//   weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
// });

const interFont = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});
const robotoFont = Roboto_Condensed({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});
const poppinsFont = Poppins({
  subsets: ["latin"],
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Streams Web Ap",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${interFont.variable} ${robotoFont.variable} ${poppinsFont.variable}`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
